// ==========================================
// GA DISPATCHER - DATENBANK V47 (THE STORYTELLER UPDATE)
// ==========================================

// 1. CORE AIRPORTS (Fallback & Europa-Fokus)
const coreDB = { 
    "EDTW": { icao: "EDTW", n: "Winzeln-Schramberg1", lat: 48.279, lon: 8.428 }, 
    "EDTF": { icao: "EDTF", n: "Freiburg1", lat: 48.023, lon: 7.828 },
    "EDNY": { icao: "EDNY", n: "Friedrichshafen", lat: 47.671, lon: 9.511 }, 
    "EDDS": { icao: "EDDS", n: "Stuttgart", lat: 48.689, lon: 9.221 },
    "EDMA": { icao: "EDMA", n: "Augsburg", lat: 48.42, lon: 10.93 }, 
    "EDJA": { icao: "EDJA", n: "Memmingen", lat: 47.98, lon: 10.23 },
    "EDTD": { icao: "EDTD", n: "Donaueschingen", lat: 47.97, lon: 8.52 }, 
    "EDTY": { icao: "EDTY", n: "Schwäbisch Hall", lat: 49.11, lon: 9.77 },
    "EDRK": { icao: "EDRK", n: "Koblenz", lat: 50.32, lon: 7.52 }, 
    "EDKB": { icao: "EDKB", n: "Bonn-Hangelar", lat: 50.76, lon: 7.16 },
    "EDLN": { icao: "EDLN", n: "Mönchengladbach", lat: 51.23, lon: 6.50 }, 
    "EDLP": { icao: "EDLP", n: "Paderborn", lat: 51.61, lon: 8.61 },
    "EDVE": { icao: "EDVE", n: "Braunschweig", lat: 52.31, lon: 10.55 }, 
    "EDDB": { icao: "EDDB", n: "Berlin-Brand.", lat: 52.36, lon: 13.50 },
    "EDDH": { icao: "EDDH", n: "Hamburg", lat: 53.63, lon: 9.98 }, 
    "EDDW": { icao: "EDDW", n: "Bremen", lat: 53.04, lon: 8.78 },
    "EDXW": { icao: "EDXW", n: "Sylt", lat: 54.91, lon: 8.34 }, 
    "EDHL": { icao: "EDHL", n: "Lübeck", lat: 53.80, lon: 10.71 },
    "LOWI": { icao: "LOWI", n: "Innsbruck", lat: 47.26, lon: 11.34 }, 
    "LOWS": { icao: "LOWS", n: "Salzburg", lat: 47.79, lon: 13.00 },
    "LOWK": { icao: "LOWK", n: "Klagenfurt", lat: 46.64, lon: 14.33 }, 
    "LOWG": { icao: "LOWG", n: "Graz", lat: 46.99, lon: 15.43 },
    "LSZH": { icao: "LSZH", n: "Zürich", lat: 47.46, lon: 8.54 }, 
    "LSGG": { icao: "LSGG", n: "Genf", lat: 46.23, lon: 6.10 },
    "LFSB": { icao: "LFSB", n: "Basel", lat: 47.59, lon: 7.52 }, 
    "LFMN": { icao: "LFMN", n: "Nizza", lat: 43.66, lon: 7.21 },
    "LFML": { icao: "LFML", n: "Marseille", lat: 43.43, lon: 5.21 }, 
    "LFPB": { icao: "LFPB", n: "Paris-Le Bourget", lat: 48.96, lon: 2.44 },
    "LIML": { icao: "LIML", n: "Mailand-Linate", lat: 45.44, lon: 9.27 }, 
    "LIPZ": { icao: "LIPZ", n: "Venedig", lat: 45.50, lon: 12.35 },
    "EDMO": { icao: "EDMO", n: "Oberpfaffenhofen", lat: 48.08, lon: 11.28 }, 
    "EDDM": { icao: "EDDM", n: "München", lat: 48.35, lon: 11.78 }
};

// 2. STANDARD MISSIONEN (A nach B - Flugplätze)
const missions = [
    // === VEREINS- UND PRIVATFLIEGEREI ===
    { t: "$100 Hamburger", i: "🍔", cat: "std", s: "Zeit für den klassischen Burger-Run! Das Flugplatz-Restaurant am Ziel soll fantastisch sein." },
    { t: "$100 Hamburger", i: "🍔", cat: "std", s: "Ein Fliegerkumpel hat dir vom neuen BBQ-Grill am Zielplatz erzählt. Das musst du checken!" },
    { t: "$100 Hamburger", i: "🍔", cat: "std", s: "Der Magen knurrt, die Sonne scheint. Flieg rüber und gönn dir das legendäre Schnitzel am Pistenrand." },
    { t: "Tagesausflug", i: "🎒", cat: "std", s: "Einfach mal raus! Schnapp dir Freunde oder Familie für einen entspannten Tag am Zielort." },
    { t: "Tagesausflug", i: "🎒", cat: "std", s: "Die Wanderwege rund um den Zielplatz rufen. Ein perfekter VFR-Hüpfer zum Abschalten." },
    { t: "Städtetrip", i: "🏙️", cat: "std", s: "Ein Wochenende in der Stadt. Parke die Maschine am GAT, bestell ein Taxi und ab ins Hotel." },
    { t: "Städtetrip", i: "🏙️", cat: "std", s: "Heute Abend gibt es ein Konzert am Zielort. Flieg rechtzeitig los, damit du pünktlich in der City bist." },
    { t: "Flugplatzfest-Logistik", i: "🎉", cat: "std", s: "Unser Vereinsfest steht an! Du musst dringend noch Banner und Equipment vom Nachbarverein holen." },
    { t: "Flugplatzfest-Logistik", i: "🎉", cat: "std", s: "Die Band fürs Abendprogramm hat ihren Tourbus geschrottet. Hol den Sänger am Zielplatz ab!" },
    { t: "Teile für die Vereinsmaschine", i: "⚙️", cat: "std", s: "Die Vereins-Cessna hat einen defekten Magnetos. Hol das neue Bauteil beim Avionik-Shop am Zielplatz ab." },
    { t: "Teile für die Vereinsmaschine", i: "⚙️", cat: "std", s: "Wir brauchen dringend neue Hauptfahrwerksreifen für den Schulungsflieger. Liegen am Ziel bereit." },
    { t: "Kollegen-Hilfe", i: "🔑", cat: "std", s: "Ein Vereinsmitglied musste die Maschine wegen Schlechtwetter stehen lassen. Flieg hin und bring sie heim!" },
    { t: "Kollegen-Hilfe", i: "🔑", cat: "std", s: "Ein Kumpel hat am Zielort den Flugzeugschlüssel im Tower liegen lassen. Du machst den Express-Kurier." },
    { t: "Piloten-Stammtisch", i: "🍻", cat: "std", s: "Treffen mit befreundeten Piloten aus der Region am Zielplatz. Alkoholfreies Bier für den Rückflug ist gebongt!" },
    { t: "Piloten-Stammtisch", i: "🍻", cat: "std", s: "Die Jahresversammlung des Regional-Aeroclubs steht an. Vertritt deinen Heimatplatz würdig." },
    { t: "Fly-In Event", i: "🎪", cat: "std", s: "Großes GA-Treffen (Fly-In) am Zielort. Mach dich auf viel Traffic in der Platzrunde gefasst!" },
    { t: "Fly-In Event", i: "🎪", cat: "std", s: "Oldtimer-Treffen am Zielplatz. Putz die Scheiben, heute wird viel fotografiert am Apron." },
    { t: "Kuchen-Express", i: "🍰", cat: "std", s: "Die legendäre Schwarzwälder Kirschtorte vom Flugplatzcafé am Zielort ruft. Ein reiner Genussflug!" },
    { t: "Kuchen-Express", i: "🍰", cat: "std", s: "Sonntagnachmittag. Die Oma deiner Passagiere wohnt nahe dem Ziel und hat frischen Apfelkuchen gebacken." },

    // === BUSINESS & LOGISTIK ===
    { t: "Business Charter", i: "🧑‍💼", cat: "std", s: "Ein lokaler Unternehmer muss zu einem Meeting. Pünktlichkeit zählt!" },
    { t: "Business Charter", i: "🧑‍💼", cat: "std", s: "Ein Architekten-Team muss zur Bauabnahme. Fliege weich, sie arbeiten an ihren Laptops." },
    { t: "Business Charter", i: "🧑‍💼", cat: "std", s: "Wichtige Investoren. Wenn der Flug angenehm wird, springt vielleicht ein Dauerauftrag für dich raus." },
    { t: "Organtransport", i: "🚑", cat: "std", s: "HÖCHSTE PRIORITÄT: Ein Spenderorgan muss sofort geliefert werden." },
    { t: "Organtransport", i: "🚑", cat: "std", s: "Dringendes Blutplasma für eine Operation am Zielort. Funk 'Medical Flight' für Priorität." },
    { t: "AOG Ersatzteil", i: "🔧", cat: "std", s: "Technik-Support: Ein Bauteil für eine gestrandete Maschine am Zielort liefern." },
    { t: "AOG Ersatzteil", i: "🔧", cat: "std", s: "Ein ADAC-Rettungshubschrauber am Ziel braucht dringend ein neues Hydraulik-Ventil. Beeilung!" },
    { t: "VIP Transfer", i: "🍾", cat: "std", s: "Ein Gast möchte diskret reisen. Komfort einplanen." },
    { t: "VIP Transfer", i: "🍾", cat: "std", s: "Ein bekannter Politiker flieht vor der Presse. Parke nach der Landung abseits des Terminals." },
    { t: "Uhren-Logistik", i: "⌚", cat: "std", s: "Wertvolle Fracht. Die Versicherung verlangt eine sanfte Landung." },
    { t: "Uhren-Logistik", i: "⌚", cat: "std", s: "Prototypen-Schmuck für eine Messe. Ein Sicherheitsbeamter fliegt auf dem Co-Pilotensitz mit." },
    { t: "Hunderettung", i: "🐾", cat: "std", s: "Tiere aus dem Tierschutz zu neuen Besitzern fliegen." },
    { t: "Hunderettung", i: "🐾", cat: "std", s: "Zwei Welpen müssen verlegt werden. Sorge für eine ruhige, warme Kabine." },
    { t: "Labor-Kurier", i: "🧪", cat: "std", s: "Zeitkritische biologische Proben. Die Kühlkette ist aktiv." },
    { t: "Labor-Kurier", i: "🧪", cat: "std", s: "Wasserproben eines Umweltlabors. Sie dürfen auf keinen Fall starken G-Kräften ausgesetzt werden." },
    { t: "Horse-Vet", i: "🐎", cat: "std", s: "Ein spezialisierter Tierarzt muss zu einem Notfall auf einem Gestüt." },
    { t: "Horse-Vet", i: "🐎", cat: "std", s: "Ein Olympia-Pferd hat sich verletzt. Der Star-Veterinär ist an Bord und nervös." },
    { t: "Urgent Mail", i: "📂", cat: "std", s: "Wichtige Dokumente müssen vor Geschäftsschluss zugestellt werden." },
    { t: "Urgent Mail", i: "📂", cat: "std", s: "Gerichtsbeweise, die noch heute dem Richter vorliegen müssen. Ein echter Wettlauf gegen die Zeit." },
    { t: "Music Producer", i: "🎧", cat: "std", s: "Ein Produzent muss mitsamt Equipment zum Studio." },
    { t: "Music Producer", i: "🎧", cat: "std", s: "Der DJ hat seinen Flug verpasst und muss in 2 Stunden auf dem Festival am Zielort auflegen!" },
    { t: "Medicine Emergency", i: "💊", cat: "std", s: "Spezialmedikamente für eine abgelegene Klinik." },
    { t: "Medicine Emergency", i: "💊", cat: "std", s: "Anti-Serum für einen seltenen Schlangenbiss. Geh direkt auf Kurs und fordere Directs beim ATC an." },
    { t: "Archive Transport", i: "📜", cat: "std", s: "Alte, wertvolle Dokumente müssen in ein neues Archiv." },
    { t: "Flower Delivery", i: "🌹", cat: "std", s: "Frische Blumen für eine Hochzeit." },
    { t: "Flower Delivery", i: "🌹", cat: "std", s: "Exotische Rosen für ein Gala-Event. Temperaturkontrolle ist hier das A und O." },
    { t: "Relocation Flight", i: "📦", cat: "std", s: "Jemand zieht um und hat das wichtigste Hab und Gut dabei." },
    { t: "High Priority Courier", i: "📦", cat: "std", s: "Ein extrem wichtiges Paket muss noch heute zugestellt werden." },
    { t: "Skydiver Drop", i: "🪂", cat: "std", s: "Bringe ein Team von Fallschirmspringern zum Zielplatz für ein Event." },
    { t: "Skydiver Drop", i: "🪂", cat: "std", s: "Ein Filmteam dreht einen Stunt am Ziel. Du fliegst die Kameraleute hin." },
    { t: "Art Transfer", i: "🖼️", cat: "std", s: "Ein wertvolles Gemälde wird zu einer Galerie geflogen. Vermeide harte Manöver." },
    { t: "Ferry Flight", i: "🛠️", cat: "std", s: "Die Maschine muss zur großen Jahresnachprüfung (JNP) in die Werft." },
    { t: "Ferry Flight", i: "🛠️", cat: "std", s: "Das Flugzeug wurde verkauft. Überführe es an den neuen Eigentümer am Zielplatz." },
    { t: "Casino Run", i: "🎰", cat: "std", s: "High-Roller wollen einen Abend im Casino verbringen. Geld spielt keine Rolle." },
    { t: "VFR Night Flight", i: "🌃", cat: "std", s: "Plane eine Landung bei Nacht am Zielort ein." },
    { t: "VFR Night Flight", i: "🌃", cat: "std", s: "Rückflug spät am Abend. Genieß das Lichtermeer der Städte unter dir!" },
    { t: "Glider Tow Pilot", i: "🪂", cat: "std", s: "Überführung eines Schleppflugzeugs zu einem Segelflugplatz." },

    // === TRAININGS-MISSIONEN ===
    { t: "Training: Stall & Recovery", i: "🎓", cat: "trn", s: "Steigflug auf 4000ft AGL. Übe Power-Off (Approach) und Power-On (Departure) Stalls. Halte den Ball stur in der Mitte!" },
    { t: "Training: Stall Practice", i: "🎓", cat: "trn", s: "Fokus auf Clean-Configuration Stalls heute. Keine Toleranz für hängende Flächen!" },
    { t: "Training: VOR Navigation", i: "🧭", cat: "trn", s: "Schalte das GPS ab! Finde das nächste VOR auf der Karte, schneide das 180° Radial an und folge ihm mit korrektem Windvorhaltewinkel." },
    { t: "Training: Steep Turns", i: "🔄", cat: "trn", s: "Das Zielgebiet eignet sich perfekt für Luftmanöver. Führe 45° Steilkurven links und rechts durch. Toleranz: max +/- 50ft Höhe!" },
    { t: "Training: Steep Turns", i: "🔄", cat: "trn", s: "Führe Steilkurven durch und achte auf den Trimm-Einsatz, sobald du an der 30°-Marke vorbeigehst." },
    { t: "Training: Engine Out (Sim)", i: "🔥", cat: "trn", s: "Auf halber Strecke zieht der Instructor das Gas auf Leerlauf. Trimm auf beste Gleitgeschwindigkeit und such dir ein Feld!" },
    { t: "Training: Engine Out (Pattern)", i: "🔥", cat: "trn", s: "Instructor zieht das Gas im Gegenanflug! Zeig, wie du aus der Platzrunde als Segler sicher auf der Piste landest." },
    { t: "Training: Pattern Drill", i: "🛫", cat: "trn", s: "Am Zielort machen wir Platzrunden-Drill. 3x Touch-and-Go. Achte exakt auf die Platzrundenhöhe und funke sauber." },
    { t: "Training: Short Pattern", i: "🛫", cat: "trn", s: "Fokus auf extrem enge Platzrunden am Zielort. Arbeite zügig mit Klappen und Trimmung, verliere keine Zeit." },
    { t: "Training: Short Field", i: "🛑", cat: "trn", s: "Simuliere am Zielort eine Landung auf extrem kurzer Piste. Punktlandung auf der Schwelle und maximales Bremsen gefordert." },
    { t: "Training: Slow Flight", i: "🐢", cat: "trn", s: "Bringe die Maschine in den Bereich minimaler Steuerbarkeit. Halte Höhe und Kurs nur mit dem Gashebel." },
    { t: "Training: Dead Reckoning", i: "🗺️", cat: "trn", s: "Koppelnavigation pur: Navigiere nur mit Karte, Stoppuhr und Kompass zum Ziel. Gleiche markante Wegpunkte visuell ab." },
    { t: "Training: Visual Nav", i: "🧭", cat: "trn", s: "Wir folgen heute nur Flüssen und Autobahnen. Schalte das GPS im Cockpit komplett ab." },
    { t: "Training: Lazy Eights", i: "♾️", cat: "trn", s: "Perfektioniere deine Seitenruder-Koordination mit Lazy Eights und Chandelles auf dem Weg zum Ziel." },
    { t: "Training: No-Flap Landing", i: "🚫", cat: "trn", s: "Wir simulieren einen Ausfall der Klappen-Elektrik. Fliege den Anflug etwas schneller und nutze den Forward Slip." },
    { t: "Training: Crosswind Mastery", i: "💨", cat: "trn", s: "Das Ziel meldet fiesen Seitenwind. Übe den 'Wing-Low' Anflug und setze exakt auf dem Luv-Rad zuerst auf." },
    { t: "Training: Emergency Descent", i: "📉", cat: "trn", s: "Simuliere Kabinenbrand auf der Route. Leite einen sofortigen Notabstieg (Spirale) ein." },
    { t: "Training: Diversion", i: "↪️", cat: "trn", s: "Simuliere eine plötzliche Streckenänderung kurz vor dem Ziel wegen Wetterverschlechterung." },
    { t: "Training: Avionics Failure", i: "📟", cat: "trn", s: "Decke das Glass-Cockpit ab! Fliege den gesamten Anflug nur mit den analogen Basis-Instrumenten (Sixpack)." },
    { t: "Flight Review (BFR)", i: "📝", cat: "trn", s: "Dein Checkflug steht an! Der Prüfer sitzt rechts. Fliege absolut nach Lehrbuch. Jede Höhe auf 10 Fuß genau." }
];

// 3. POI MISSIONEN (Generischer Fallback)
const poiMissions = [
    { t: "Foto-Tour", i: "📸", cat: "poi", s: "Ein Fotograf an Bord braucht die perfekte Perspektive auf das Ziel." },
    { t: "VIP-Sightseeing", i: "🍾", cat: "poi", s: "Fluggäste haben einen Rundflug gebucht, um das Wahrzeichen von oben zu sehen." },
    { t: "Naturwacht", i: "🚁", cat: "poi", s: "Kreise über dem Zielgebiet und dokumentiere Auffälligkeiten für die Behörden." },
    { t: "Luftvermessung", i: "📏", cat: "poi", s: "Fliege in präziser Höhe über das Objekt für topografische Scans." }
];

// 4. FALLBACK POIs (Fokus D-A-CH & Europa)
const fallbackPOIs = [
    { n: "Triberger Wasserfälle", lat: 48.127, lon: 8.227 },
    { n: "Feldberg (Gipfel)", lat: 47.873, lon: 8.004 },
    { n: "Titisee", lat: 47.896, lon: 8.148 },
    { n: "Schluchsee", lat: 47.818, lon: 8.181 },
    { n: "Burg Hohengeroldseck", lat: 48.338, lon: 7.979 },
    { n: "Vogtsbauernhof (Gutach)", lat: 48.270, lon: 8.199 },
    { n: "Europapark Rust", lat: 48.266, lon: 7.721 },
    { n: "Burg Hohenzollern", lat: 48.323, lon: 8.967 },
    { n: "Schloss Sigmaringen", lat: 48.087, lon: 9.216 },
    { n: "Insel Mainau (Bodensee)", lat: 47.705, lon: 9.195 },
    { n: "Burg Meersburg", lat: 47.693, lon: 9.271 },
    { n: "Mummelsee (Schwarzwald)", lat: 48.597, lon: 8.200 },
    { n: "Schloss Heidelberg", lat: 49.410, lon: 8.715 },
    { n: "Burg Teck", lat: 48.588, lon: 9.470 },
    { n: "Schloss Neuschwanstein", lat: 47.557, lon: 10.750 },
    { n: "Zugspitze (Gipfel)", lat: 47.421, lon: 10.985 },
    { n: "Watzmann (Gipfel)", lat: 47.554, lon: 12.924 },
    { n: "Kölner Dom", lat: 50.941, lon: 6.958 },
    { n: "Berliner Fernsehturm", lat: 52.520, lon: 13.409 },
    { n: "Brandenburger Tor", lat: 52.516, lon: 13.377 },
    { n: "Brocken (Harz)", lat: 51.799, lon: 10.615 },
    { n: "Loreley (Rhein)", lat: 50.139, lon: 7.728 },
    { n: "Burg Eltz", lat: 50.205, lon: 7.336 },
    { n: "Basteibrücke (Elbsandstein)", lat: 50.961, lon: 14.073 },
    { n: "Frauenkirche Dresden", lat: 51.052, lon: 13.741 },
    { n: "Hermannsdenkmal", lat: 51.911, lon: 8.839 },
    { n: "Schweriner Schloss", lat: 53.624, lon: 11.419 },
    { n: "Externsteine", lat: 51.868, lon: 8.917 },
    { n: "Völkerschlachtdenkmal", lat: 51.312, lon: 12.413 },
    { n: "Kreidefelsen Rügen", lat: 54.573, lon: 13.664 },
    { n: "Elbphilharmonie Hamburg", lat: 53.541, lon: 9.984 },
    { n: "Walhalla (Regensburg)", lat: 49.031, lon: 12.212 },
    { n: "Zeche Zollverein", lat: 51.486, lon: 7.046 },
    { n: "Matterhorn (CH)", lat: 45.976, lon: 7.658 },
    { n: "Jungfraujoch (CH)", lat: 46.547, lon: 7.982 },
    { n: "Rheinfall (CH)", lat: 47.677, lon: 8.615 },
    { n: "Aletschgletscher (CH)", lat: 46.463, lon: 8.037 },
    { n: "Großglockner (AT)", lat: 47.074, lon: 12.693 },
    { n: "Schloss Schönbrunn (AT)", lat: 48.184, lon: 16.312 },
    { n: "Festung Hohensalzburg (AT)", lat: 47.795, lon: 13.047 },
    { n: "Mont Blanc (FR)", lat: 45.832, lon: 6.865 },
    { n: "Eiffelturm (FR)", lat: 48.858, lon: 2.294 },
    { n: "Mont Saint-Michel (FR)", lat: 48.636, lon: -1.511 },
    { n: "Viaduc de Millau (FR)", lat: 44.077, lon: 3.022 },
    { n: "Colosseum Rom (IT)", lat: 41.890, lon: 12.492 },
    { n: "Vesuv (IT)", lat: 40.822, lon: 14.426 },
    { n: "Ätna (IT)", lat: 37.751, lon: 14.993 },
    { n: "Sagrada Familia (ES)", lat: 41.403, lon: 2.174 },
    { n: "Stonehenge (UK)", lat: 51.178, lon: -1.826 },
    { n: "Akropolis Athen (GR)", lat: 37.971, lon: 23.725 }
];